name: Get buildings information

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"

      - name: Install Poetry
        run: |
          pip install poetry 
          poetry install --no-root

      - name: Run tests with pytest
        run: |
          poetry run pytest tests/apis/test_get_department.py       
