name: Build online documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.8"

      - name: Install Poetry and rebuilding poetry.lock
        run: |
          pip install poetry 
          poetry install --no-root

      - name: Build documentation
        run: |
          poetry run make html --directory docs/
