name: Get weather information

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"
          
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-root

      - name: Configure AWS Credentials
        env:
          DVC_AWS_ACCESS_KEY_ID: ${{ secrets.DVC_AWS_ACCESS_KEY_ID }}
          DVC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DVC_AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "aws-access-key-id=${DVC_AWS_ACCESS_KEY_ID}" >> ~/.aws/config
          echo "aws-secret-access-key=${DVC_AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
          echo "aws-region=eu-north-1" >> ~/.aws/config
          
      - name: Pull DVC data from S3 bucket
        run: |
          poetry run dvc pull --allow-missing

      - name: Run tests with pytest
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: |
          poetry run pytest --cov tests/apis/weather/
