name: Get Weather Information

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.8"

      - name: Install Poetry
        run: |
          pip install poetry 
          poetry install --no-root

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[dvc]" > ~/.aws/config 
          echo "aws_access_key_id=${{ secrets.DVC_AWS_ACCESS_KEY_ID }}" >> ~/.aws/config
          echo "aws_secret_access_key=${{ secrets.DVC_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/config
          echo "region=eu-north-1" >> ~/.aws/config

      - name: Check AWS Configuration
        run: |
          cat ~/.aws/config  # Print the AWS config for debugging purposes
          aws configure list-profiles

      - name: Run DVC Doctor
        run: poetry run dvc doctor

      - name: Clean DVC Temporary Files
        run: rm -rf .dvc/tmp

      - name: Pull DVC data from S3 bucket
        env:
          AWS_PROFILE: dvc  # Ensure this matches the profile in your AWS config
        run: |
          poetry run dvc pull --allow-missing -v  # Use verbose output for debugging

      - name: Run tests with pytest
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: |
          poetry run pytest --cov tests/apis/weather/
