name: Get weather information

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"

      - name: Install Poetry
        run: |
          pip install poetry 
          poetry install

      - name: Install DVC with AWS support
        run: |
          poetry add dvc[aws]

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DVC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DVC_AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "[default]" > ~/.aws/config
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config

      - name: Pull DVC data from S3 bucket
        run: |
          dvc pull --allow-missing

      - name: Run tests with pytest
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: |
          poetry run pytest               
